// 用 edge-tts 合成「开机离线提示音」并写成固件可直接 #include 的 C 头文件。
//
// 用法（在 backend 目录）：
//   npm run gen:boot-sound -- "植物管家已启动"
//   TTS_VOICE=zh-CN-YunxiNeural npm run gen:boot-sound -- "你好呀"
//
// 输出：firmware/src/boot_sound.h（内置 24kHz 单声道 MP3 字节数组）。
// 复用 src/services/edgeTts.ts（已含 Sec-MS-GEC 令牌修复），与后端 /internal/tts 同源。
import { writeFileSync } from "node:fs";
import { synthesizeMp3 } from "../src/services/edgeTts.js";

const text = process.argv[2] || "植物管家已启动";
const voice = process.env.TTS_VOICE || "zh-CN-XiaoxiaoNeural";

const buf = await synthesizeMp3(text, voice);
if (buf.length === 0) {
  console.error("synthesis produced 0 bytes");
  process.exit(1);
}

let out = "#pragma once\n";
out += "// AUTO-GENERATED by backend/scripts/genBootSound.ts\n";
out += `// text: ${text}  voice: ${voice}  bytes: ${buf.length}\n`;
out += "#define HAS_BOOT_SOUND 1\n";
out += "static const unsigned char BOOT_SOUND_MP3[] = {\n";
for (let i = 0; i < buf.length; i++) {
  out += buf[i] + ",";
  if (i % 20 === 19) out += "\n";
}
out += `\n};\nstatic const unsigned int BOOT_SOUND_MP3_LEN = ${buf.length};\n`;

const target = new URL("../../firmware/src/boot_sound.h", import.meta.url);
writeFileSync(target, out);
console.log(`wrote firmware/src/boot_sound.h (${buf.length} bytes MP3, voice=${voice})`);
